# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170723_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.Category')),
            ],
            bases=('products.category',),
        ),
    ]
