# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Category')),
                ('subcategories', models.ManyToManyField(to='products.Subcategory')),
            ],
            bases=('products.category',),
        ),
    ]
